# Generated by Django 5.2.6 on 2025-10-03 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadCliente',
            fields=[
                ('idCliente', models.AutoField(primary_key=True, serialize=False)),
                ('razaoSocial', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('inscEstadual', models.CharField(blank=True, max_length=20, null=True)),
                ('inscMunicipal', models.CharField(blank=True, max_length=20, null=True)),
                ('logradouro', models.CharField(max_length=255)),
                ('numeroLogradouro', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=255)),
                ('sgEstado', models.CharField(max_length=2)),
                ('pais', models.CharField(max_length=255)),
                ('cep', models.CharField(max_length=8)),
                ('telefone', models.CharField(max_length=20)),
                ('dataCadastro', models.DateField(auto_now_add=True)),
                ('dataAtualizacao', models.DateField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('situacao', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CadVeic',
            fields=[
                ('idVeic', models.AutoField(primary_key=True, serialize=False)),
                ('tpVeiculo', models.CharField(max_length=100)),
                ('tpVeiculoQualp', models.CharField(blank=True, max_length=100, null=True)),
                ('eixos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('idRota', models.AutoField(primary_key=True, serialize=False)),
                ('codRota', models.IntegerField(unique=True)),
                ('origem', models.CharField(max_length=255)),
                ('destino', models.CharField(max_length=255)),
                ('km', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CotacaoBid',
            fields=[
                ('idCotacaoBid', models.AutoField(primary_key=True, serialize=False)),
                ('nCotacaoBid', models.CharField(max_length=50, unique=True, verbose_name='Número da Cotação')),
                ('dataCriacao', models.DateField(auto_now_add=True)),
                ('rounds', models.IntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotacao.cadcliente')),
            ],
        ),
        migrations.CreateModel(
            name='DetalheCotacaoBid',
            fields=[
                ('idDetCotBid', models.AutoField(primary_key=True, serialize=False)),
                ('origem', models.CharField(max_length=255)),
                ('destino', models.CharField(max_length=255)),
                ('tpVeiculoQualp', models.CharField(max_length=100)),
                ('eixos', models.IntegerField()),
                ('km', models.IntegerField()),
                ('pedagio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('freteMinimo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('round1', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('round2', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('round3', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('round4', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('round5', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cadVeiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotacao.cadveic')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotacao.cadcliente')),
                ('cotacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalhes', to='cotacao.cotacaobid')),
                ('codRota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotacao.rota')),
            ],
        ),
    ]
