# Generated by Django 5.2.6 on 2025-10-03 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadcliente',
            name='cep',
            field=models.CharField(max_length=9),
        ),
    ]
