# Generated by Django 5.2.6 on 2025-10-07 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotacao', '0002_alter_cadcliente_cep'),
    ]

    operations = [
        migrations.CreateModel(
            name='tabelaANTT',
            fields=[
                ('idTabelaANTT', models.AutoField(primary_key=True, serialize=False)),
                ('codTabelaANTT', models.CharField(blank=True, max_length=7, null=True, unique=True)),
                ('Descricao', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='detalhecotacaobid',
            name='codRota',
            field=models.CharField(max_length=255),
        ),
        migrations.RenameField(
            model_name='cotacaobid',
            old_name='cliente',
            new_name='idCliente',
        ),
        migrations.RenameField(
            model_name='detalhecotacaobid',
            old_name='idDetCotBid',
            new_name='idDetCotacao',
        ),
        migrations.AlterField(
            model_name='cotacaobid',
            name='rounds',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='detalhecotacaobid',
            name='destino',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='detalhecotacaobid',
            name='eixos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detalhecotacaobid',
            name='freteMinimo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='detalhecotacaobid',
            name='km',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detalhecotacaobid',
            name='origem',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='detalhecotacaobid',
            name='pedagio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cotacaobid',
            name='tabelaANTT',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cotacao.tabelaantt'),
        ),
        migrations.DeleteModel(
            name='Rota',
        ),
    ]
