# Generated by Django 5.2.6 on 2025-10-07 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotacao', '0003_tabelaantt_alter_detalhecotacaobid_codrota_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tabelaantt',
            old_name='Descricao',
            new_name='descricao',
        ),
    ]
