# Generated by Django 5.2.6 on 2025-10-07 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotacao', '0004_rename_descricao_tabelaantt_descricao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tabelaantt',
            old_name='descricao',
            new_name='Descricao',
        ),
    ]
