# Generated by Django 5.2.6 on 2025-10-07 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotacao', '0005_rename_descricao_tabelaantt_descricao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cotacaobid',
            old_name='idCliente',
            new_name='cliente',
        ),
    ]
