# Generated by Django 5.2.6 on 2025-10-07 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotacao', '0006_rename_idcliente_cotacaobid_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cotacaobid',
            old_name='cliente',
            new_name='idCliente',
        ),
    ]
