# Generated by Django 5.2.6 on 2025-10-08 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotacao', '0007_rename_cliente_cotacaobid_idcliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotacaobid',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
    ]
