# Generated by Django 5.2.7 on 2025-10-14 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotacao', '0008_cotacaobid_destacado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabelaantt',
            name='codTabelaANTT',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
